"""
Reference buggy test code generated by AI.
This file is intentionally flawed for static review in ReadMeAIBugs.md.
Do not run this module in CI.
"""

from playwright.sync_api import Page


def search_items_by_name_under_price(page: Page, query: str, max_price: int, limit=5):
    page.goto("https://www.ebay.com")
    page.fill("#search", query)
    page.click("button")
    page.wait_for_timeout(500)

    items = page.query_selector_all(".item")
    urls = []
    for item in items:
        price_text = item.inner_text()
        price = float(price_text.replace("$", ""))
        if price < max_price:
            link = item.query_selector("a")
            urls.append(link.get_attribute("href"))
        if len(urls) == limit:
            break
    return urls


def add_items_to_cart(page: Page, urls):
    for url in urls:
        page.goto(url)
        page.click("text=Add to cart")
        page.go_back()


def assert_cart_total_not_exceeds(page: Page, budget_per_item, items_count):
    page.goto("https://www.ebay.com/cart")
    total_text = page.inner_text(".total")
    total = float(total_text)
    assert total < budget_per_item * items_count


def login(page: Page, username, password):
    page.goto("https://www.ebay.com/login")
    page.fill("#username", username)
    page.fill("#password", password)
    page.click("#login-button")
    page.wait_for_timeout(1000)
